
const API_BASE_URL = process.env.NEXT_PUBLIC_FDO_API_BASE_URL;
const API_LOCAL_BASE_URL = process.env.NEXT_PUBLIC_FDO_LOCAL_API_BASE_URL;

// -------------------------VENDOR_INTERNAL API URL -----------------------------
const CURRENCY_API_URL = process.env.NEXT_PUBLIC_CURRENCY_API_URL;
const COUNTRY_API_URL = process.env.NEXT_PUBLIC_COUNTRY_API_URL;
const EMAILVALIDATE_API_URL = process.env.NEXT_PUBLIC_EMAILVALIDATE_API_URL;
const VENDORTYPE_API_URL = process.env.NEXT_PUBLIC_VENDORTYPE_API_URL;
const TERMSOFPAYMENT_API_URL = process.env.NEXT_PUBLIC_TERMSOFPAYMENT_API_URL;
const MODEOFPAYMENT_API_URL = process.env.NEXT_PUBLIC_MODEOFPAYMENT_API_URL;
const TERMSOFDELIVERY_API_URL = process.env.NEXT_PUBLIC_TERMSOFDELIVERY_API_URL;
const CATEGORY_API_URL = process.env.NEXT_PUBLIC_CATEGORY_API_URL;
const QUESTION_API_URL = process.env.NEXT_PUBLIC_QUESTION_API_URL;
const QUATATION_API_URL = process.env.NEXT_PUBLIC_QUATATION_API_URL;
const PURCHASEORDER_API_URL = process.env.NEXT_PUBLIC_PURCHASEORDER_API_URL;

// -------------------------VENDOR_FORM API URL -----------------------------
const GENERAL_INFORMATION_FORM_API_URL = process.env.NEXT_PUBLIC_GENERALINFORMATION_API_URL;
const VENDOR_ALL_INFORMATION_API_URL = process.env.NEXT_PUBLIC_VENDORALL_INFORMATION_API_URL;



export { API_BASE_URL, CURRENCY_API_URL, COUNTRY_API_URL,API_LOCAL_BASE_URL ,EMAILVALIDATE_API_URL,VENDORTYPE_API_URL, TERMSOFPAYMENT_API_URL, MODEOFPAYMENT_API_URL, TERMSOFDELIVERY_API_URL, CATEGORY_API_URL, QUESTION_API_URL, QUATATION_API_URL, PURCHASEORDER_API_URL,GENERAL_INFORMATION_FORM_API_URL,VENDOR_ALL_INFORMATION_API_URL};
