
const API_BASE_URL = process.env.NEXT_PUBLIC_FDO_API_BASE_URL;
const API_LOCAL_BASE_URL = process.env.NEXT_PUBLIC_FDO_LOCAL_API_BASE_URL;

// -------------------------VENDOR_INTERNAL API URL -----------------------------
const CURRENCY_API_URL = process.env.NEXT_PUBLIC_CURRENCY_API_URL;
const COUNTRY_API_URL = process.env.NEXT_PUBLIC_COUNTRY_API_URL;
const EMAILVALIDATE_API_URL = process.env.NEXT_PUBLIC_EMAILVALIDATE_API_URL;
const VENDORTYPE_API_URL = process.env.NEXT_PUBLIC_VENDORTYPE_API_URL;
const TERMSOFPAYMENT_API_URL = process.env.NEXT_PUBLIC_TERMSOFPAYMENT_API_URL;
const MODEOFPAYMENT_API_URL = process.env.NEXT_PUBLIC_MODEOFPAYMENT_API_URL;
const TERMSOFDELIVERY_API_URL = process.env.NEXT_PUBLIC_TERMSOFDELIVERY_API_URL;
const CATEGORY_API_URL = process.env.NEXT_PUBLIC_CATEGORY_API_URL;
const QUESTION_API_URL = process.env.NEXT_PUBLIC_QUESTION_API_URL;
const QUATATION_API_URL = process.env.NEXT_PUBLIC_QUATATION_API_URL;
const PURCHASEORDER_API_URL = process.env.NEXT_PUBLIC_PURCHASEORDER_API_URL;

// -------------------------VENDOR_FORM API URL -----------------------------
const VENDOR_ALL_INFORMATION_API_URL = process.env.NEXT_PUBLIC_VENDORALL_INFORMATION_API_URL;
const GENERAL_INFORMATION_FORM_API_URL = process.env.NEXT_PUBLIC_GENERALINFORMATION_API_URL;
const COMPANYDETAIL_API_URL = process.env.NEXT_PUBLIC_COMPANY_INFORMATION_API_URL;
const TAXBILLING_API_URL = process.env.NEXT_PUBLIC_TAXBILLING_INFORMATION_API_URL;
const ACCOUNTDETAIL_API_URL = process.env.NEXT_PUBLIC_ACCOUNTDETAIL_INFORMATION_API_URL;
const QUESTIONAIRE_API_URL = process.env.NEXT_PUBLIC_QUESTIONAIRE_INFORMATION_API_URL;
const VENDORATTACHMENT_API_URL = process.env.NEXT_PUBLIC_VENDORATTACHMENT_INFORMATION_API_URL;
const OTHERDETAILS_API_URL = process.env.NEXT_PUBLIC_OTHERDETAILS_INFORMATION_API_URL;
const VENDOR_APPROVAL_API_URL = process.env.NEXT_PUBLIC_VENDOR_APPROVAL_API_URL;
const VERIFY_VENDORDATA_API_URL = process.env.NEXT_PUBLIC_VERIFY_VENDORDATA_API_URL;

// -------------------------AUTHENTICATION API URL -----------------------------
const LOGIN_API_URL = process.env.NEXT_PUBLIC_LOGIN_API_URL;
const OTPVALIDATE_API_URL = process.env.NEXT_PUBLIC_OTPVALIDATE_API_URL;
const REGISTER_API_URL = process.env.NEXT_PUBLIC_REGISTER_API_URL;
const OTPVERIFY_API_URL = process.env.NEXT_PUBLIC_VERIFY_API_URL;
const RESEND_API_URL = process.env.NEXT_PUBLIC_RESENDOTP_API_URL;
const LOGOUT_API_URL = process.env.NEXT_PUBLIC_LOGOUT_API_URL;
const FORGOT_PASSWORD_API_URL = process.env.NEXT_PUBLIC_FORGOT_PASSWORD_API_URL;
const UPDATE_PASSWORD_API_URL = process.env.NEXT_PUBLIC_UPDATE_PASSWORD_API_URL;

// -------------------------TENDER API URL -----------------------------
const TENDERLIST_API_URL = process.env.NEXT_PUBLIC_TENDERLIST_API_URL;
const TENDERPREVIEW_API_URL = process.env.NEXT_PUBLIC_TENDERPREVIEW_API_URL;
const COMPANYLIST_API_URL = process.env.NEXT_PUBLIC_COPMANY_API_URL;
const TENDER_INTEREST_API_URL = process.env.NEXT_PUBLIC_TENDER_INTEREST_API_URL;
const INTERESTED_TENDER_LIST_API_URL = process.env.NEXT_PUBLIC_INTERESTED_TENDER_LIST_API_URL;
const INTERESTED_TENDER_VIEW_API_URL = process.env.NEXT_PUBLIC_INTERESTED_TENDER_VIEW_API_URL;
const TENDER_PAYMENT_API_URL = process.env.NEXT_PUBLIC_TENDER_PAYMENT_API_URL;
const TENDER_ADDPBG_API_URL = process.env.NEXT_PUBLIC_TENDER_ADDPBG_API_URL;
const TENDER_DELETEPBG_API_URL = process.env.NEXT_PUBLIC_TENDER_DELETEPBG_API_URL;
const TENDER_UPLOAD_REQUIRED_DOCS_API_URL = process.env.NEXT_PUBLIC_TENDER_UPLOAD_REQUIRED_DOCS_API_URL;

// -------------------------RFI API URL -----------------------------
const RFILIST_API_URL = process.env.NEXT_PUBLIC_RFILIST_API_URL;
const RFIPREVIEW_API_URL = process.env.NEXT_PUBLIC_RFIPREVIEW_API_URL;




// ----------------------Export api url---------------------
export { API_BASE_URL, CURRENCY_API_URL, COUNTRY_API_URL, API_LOCAL_BASE_URL, EMAILVALIDATE_API_URL, VENDORTYPE_API_URL, TERMSOFPAYMENT_API_URL, MODEOFPAYMENT_API_URL, TERMSOFDELIVERY_API_URL, CATEGORY_API_URL, QUESTION_API_URL, QUATATION_API_URL, PURCHASEORDER_API_URL, GENERAL_INFORMATION_FORM_API_URL, VENDOR_ALL_INFORMATION_API_URL, COMPANYDETAIL_API_URL, TAXBILLING_API_URL, ACCOUNTDETAIL_API_URL, QUESTIONAIRE_API_URL, VENDORATTACHMENT_API_URL, OTHERDETAILS_API_URL, LOGIN_API_URL, TENDERLIST_API_URL, OTPVALIDATE_API_URL, REGISTER_API_URL, OTPVERIFY_API_URL, TENDERPREVIEW_API_URL, COMPANYLIST_API_URL, VENDOR_APPROVAL_API_URL, VERIFY_VENDORDATA_API_URL, RESEND_API_URL, LOGOUT_API_URL, RFILIST_API_URL, RFIPREVIEW_API_URL, FORGOT_PASSWORD_API_URL, UPDATE_PASSWORD_API_URL, TENDER_INTEREST_API_URL, INTERESTED_TENDER_LIST_API_URL, INTERESTED_TENDER_VIEW_API_URL, TENDER_PAYMENT_API_URL, TENDER_ADDPBG_API_URL, TENDER_DELETEPBG_API_URL, TENDER_UPLOAD_REQUIRED_DOCS_API_URL };
